### ISSUE TITLE
Automated Sweep Crash

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#19]
Bigly 2.0 crashed during automated sweep jobs. I suspect it has to do with the relay disconnecting as I reloaded and had it crash again when I tried to do restart the job and the relay didn't respond. I attached the log file for your convenience. I wasn't sure when the crash occured cause I haven't checked the station since you were here on Tuesday so I included both just in case.
[ivscan-2017-03-14.txt](https://github.com/OneSunSolar/IVScan/files/851323/ivscan-2017-03-14.txt)
[ivscan-2017-03-17.txt](https://github.com/OneSunSolar/IVScan/files/851324/ivscan-2017-03-17.txt)

**Comment by markbreynolds** [comment]
Yes it looks like it crashed at 9pm, on Tuesday. I think it has something to do with holder, because after doing a measurement with holder, the relay stopped responding. I will work on making the automated sweep more resilient. Do you think it would it be better to display an error message and stop taking sweeps, or display an error message and continue taking sweeps for automated jobs?

**Comment by nfehrenbach** [comment]
If it is disconnected from the relay it should probably just display the warning since the measurements will be machine noise.

**Comment by markbreynolds** [comment]
Now will display an error in the status section of the automated job queue, when an error occurs during a job.
