### ISSUE TITLE
Wrong Area Units for Summary

### ISSUE THREAD

**Issue by markbreynolds** [OneSunSolar/IVScan#3]
Cell area is in m<sup>2</sup> instead of cm<sup>2</sup> as the labels suggest.

**Comment by nfehrenbach** [comment]
Area units fixed, but there are problems with calculating the Jsc now as the summary file value is 100x too high. This problem is only present in the summary file as the individual IV files list the correct Jsc values. The Jmax is calculated correctly currently. (Also see efficiency and fill factor representation of IV Sweep.exe log and Output files for more information on changing the Efficiency and Fill Factor reporting).

**Comment by nfehrenbach** [comment]
Area units and Jsc both reported correctly on summary now.
